"""new column on detetection

Revision ID: 2b4cffcaaecf
Revises: b7293cff7e1d
Create Date: 2026-03-03 10:00:39.538724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4cffcaaecf'
down_revision: Union[str, Sequence[str], None] = 'b7293cff7e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('image_url_result', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'image_url_result')
    # ### end Alembic commands ###
